### ISSUE TITLE
1.2.0 decorator - AttributeError: 'Retrying' object has no attribute 'getattr'

### ISSUE THREAD

**Issue by alexkuang** [rholder/retrying#4]
Hi there,

I'm getting a `AttributeError: 'Retrying' object has no attribute 'getattr'` when the `@retry` decorator is being used in `1.2.0`.  I actually ran into this while building out the dependencies for another library I'm using (dynamic-dynamodb), so apologies in advance if I'm missing something obvious about the usage.  

Here's a REPL session that roughly duplicates what that library was doing:

``` python
Python 2.7.5 (default, Sep 12 2013, 21:33:34)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from retrying import retry
>>> @retry(
...     wait='exponential_sleep',
...     wait_exponential_multiplier=1000,
...     wait_exponential_max=5000)
... def foo():
...     return 1
...
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/retrying.py", line 89, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Library/Python/2.7/site-packages/retrying.py", line 154, in __init__
    self.wait = self.getattr(wait)
AttributeError: 'Retrying' object has no attribute 'getattr'
```

It _seemed_ to work on `1.1.x` before I rebuilt this morning and the lib pulled in `1.2.0`, so I'm guessing it's something fairly recent.
